import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";               // ① 위에서 수정한 globals.css
import "../style/MainSection.css"; // ② 각 섹션별 CSS 파일
import "../style/AboutMeSection.css";
import "../style/SkillsSection.css";
import "../style/ProjectSection.css";
import "../style/ContactSection.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Paperlogy&display=swap" />
        {children}
      </body>
    </html>
  );
}
